package com.dojo.lit.util

annotation class CardApiNames {
    companion object {
        val S2 = "spades_2"
        val S3 = "spades_3"
        val S4 = "spades_4"
        val S5 = "spades_5"
        val S6 = "spades_6"
        val S7 = "spades_7"
        val S8 = "spades_8"
        val S9 = "spades_9"
        val S10 = "spades_10"
        val Sj = "spades_j"
        val Sq = "spades_q"
        val Sk = "spades_k"
        val Sa = "spades_a"

        val C2 = "clubs_2"
        val C3 = "clubs_3"
        val C4 = "clubs_4"
        val C5 = "clubs_5"
        val C6 = "clubs_6"
        val C7 = "clubs_7"
        val C8 = "clubs_8"
        val C9 = "clubs_9"
        val C10 = "clubs_10"
        val Cj = "clubs_j"
        val Cq = "clubs_q"
        val Ck = "clubs_k"
        val Ca = "clubs_a"

        val D2 = "diamonds_2"
        val D3 = "diamonds_3"
        val D4 = "diamonds_4"
        val D5 = "diamonds_5"
        val D6 = "diamonds_6"
        val D7 = "diamonds_7"
        val D8 = "diamonds_8"
        val D9 = "diamonds_9"
        val D10 = "diamonds_10"
        val Dj = "diamonds_j"
        val Dq = "diamonds_q"
        val Dk = "diamonds_k"
        val Da = "diamonds_a"

        val H2 = "hearts_2"
        val H3 = "hearts_3"
        val H4 = "hearts_4"
        val H5 = "hearts_5"
        val H6 = "hearts_6"
        val H7 = "hearts_7"
        val H8 = "hearts_8"
        val H9 = "hearts_9"
        val H10 = "hearts_10"
        val Hj = "hearts_j"
        val Hq = "hearts_q"
        val Hk = "hearts_k"
        val Ha = "hearts_a"

        val Jb = "joker_b"
        val Jr = "joker_r"
    }
}
